spring:
  profiles:
    active: notebook
mybatis:
    type-aliases-package: org.codelab.batch.dto
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
---
spring:
   profiles: notebook
   datasource:
      database: mysql
      url: jdbc:mysql://localhost:3306/codelab?useSSL=false
      username: codej99
      password: cjstk1
      driver-class-name: com.mysql.jdbc.Driver
logging:
   level:
      org.codelab.batch: INFO
---
spring:
   profiles: docker
   datasource:
      database: mysql
      url: jdbc:mysql://192.168.0.5:32771/codelab?useSSL=false
      username: codej99
      password: cjstk1
      driver-class-name: com.mysql.jdbc.Driver
logging:
   level:
      org.codelab.batch: INFO