spring:
   profiles: linux
   datasource:
      database: mysql
      jdbc-url: jdbc:mysql://192.168.0.6:3306/codelab?useSSL=false
      username: codej99
      password: kim73221722
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
         connection-test-query: SELECT 1
logging:
   level:
      org.codelab.batch: INFO
---
spring:
   profiles: notebook
   datasource:
      jdbc-url: jdbc:mysql://localhost:3306/codelab?useSSL=false
      username: codej99
      password: cjstk1
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
         connection-test-query: SELECT 1
logging:
   level:
      org.codelab.batch: INFO